{{- if and .Values.es.ssl.enabled (eq .Values.es.ssl.useExistingSecrets false) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-elasticsearch-exporter.name" . }}-cert
  labels:
    chart: {{ template "prometheus-.chart" . }}
    app: {{ template "prometheus-.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  ca.pem: {{ .Values.es.ssl.ca.pem | b64enc }}
  client.pem: {{ .Values.es.ssl.client.pem | b64enc }}
  client.key: {{ .Values.es.ssl.client.key | b64enc }}
{{- end }}
