{{- if .Values.podSecurityPolicies.enabled -}}
apiVersion: {{ template "rbac.apiVersion" . }}
kind: Role
metadata:
  name: {{ template "prometheus-elasticsearch-exporter.name" . }}
  labels:
    chart: {{ template "prometheus-.chart" . }}
    app: {{ template "prometheus-.name" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - {{ template "prometheus-.name" . }}
{{- end }}
