# Настройки эндпоинта
endpoints:
  ip: 192.168.88.2
  node: mail-sirius

# Настройки сервиса
service:
  name: metrics
  type: ClusterIP
  port: 9154

# Настройки сервисмонитора:
serviceMonitor:
  interval: 60s
  path: /metrics
  port: metrics
  scheme: http
  metricRelabelings:
    - action: keep
      regex: postfix.*
      sourceLabels:
      - __name__

# Включаем ли мы секреты
secrets:
  enabled: true