stages:
  - cpm-dev-deploy
#  - cpm-yc-deploy
#  - corp-deploy
#  - univ-deploy
#  - sirius-deploy

.base-deploy-exporter:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
    - echo 'CI_ENVIRONMENT_SLUG =>' ${CI_ENVIRONMENT_SLUG}
    - echo 'CHART_NAME =>' ${CHART_NAME}
  script:
    - set -x
    - kubectl get ns prometheus-exporters || kubectl create ns prometheus-exporters
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="${CHART_NAME}"
      NAMESPACE="prometheus-exporters"
      CHART="deploy/helm/charts/${CHART_NAME}"
      HELM_ARGS="
      -f deploy/helm/charts/${CHART_NAME}/conf/${CLUSTER_NAME}-${CI_ENVIRONMENT_SLUG}.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${GITLAB_REGISTRY}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

##############  CPM-DEV  ############

elasticsearch-exporter deploy:
  extends:
    - .base-deploy-exporter
  stage: cpm-dev-deploy
  variables:
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "cpm-dev"
  environment:
    name: stage
  tags:
    - kube-cpm

redis-exporter deploy:
  extends:
    - .base-deploy-exporter
  stage: cpm-dev-deploy
  variables:
    CHART_NAME: "prometheus-redis-exporter"
    CLUSTER_NAME: "cpm-dev"
  environment:
    name: stage
  tags:
    - kube-cpm

postgres-exporter deploy:
  extends:
    - .base-deploy-exporter
  stage: cpm-dev-deploy
  variables:
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "cpm-dev"
  environment:
    name: stage
  tags:
    - kube-cpm

##############  CPM-YC  ############
#
#cpm-yc deploy:
#  extends:
#    - .base-elasticsearch-exporter
#  stage: cpm-yc-deploy
#  variables:
#    CLUSTER_NAME: "cpm"
#  environment:
#    name: prod
#  tags:
#    - cpm-yac
#
##############  CORP  ############
#
#corp deploy:
#  extends:
#    - .base-elasticsearch-exporter
#  stage: corp-deploy
#  variables:
#    CLUSTER_NAME: "corp"
#  tags:
#    - kube-corp
#
##############  UNIV  ############
#
#univ deploy:
#  extends:
#    - .base-elasticsearch-exporter
#  stage: univ-deploy
#  variables:
#    CLUSTER_NAME: "univ"
#  tags:
#    - kube-univ
#
##############  SIRIUS  ############
#
#sirius deploy:
#  extends:
#    - .base-elasticsearch-exporter
#  stage: sirius-deploy
#  variables:
#    CLUSTER_NAME: "sirius"
#  tags:
#    - kube-ci
