stages:
  - sirius
  - univ

.prepare-deploy:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
    - echo 'CI_ENVIRONMENT_SLUG =>' ${CI_ENVIRONMENT_SLUG}
    - echo 'CHART_NAME =>' ${CHART_NAME}
    - echo 'RELEASE =>' ${RELEASE}
    - kubectl get ns prometheus-exporters || kubectl create ns prometheus-exporters
    - export access_config="${CLUSTER_NAME}_access_config"

.script-deploy:
  script:
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="${RELEASE}"
      NAMESPACE="prometheus-exporters"
      CHART="charts/${CHART_NAME}"
      HELM_ARGS="
      -f charts/${CHART_NAME}/conf/${CI_ENVIRONMENT_SLUG}/${CLUSTER_NAME}.yaml
      -f ${!access_config}
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${GITLAB_REGISTRY}"
      --set global.ngenix_user_login="${NGENIX_USER_LOGIN}"
      --set global.ngenix_user_token="${NGENIX_USER_TOKEN}"
      --set global.hosting_secret="${HOSTING_AUTH}"
      --set global.hosting_user="${HOSTING_USER}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

.helm-deploy:
  script:
    - helm upgrade --install
      ${RELEASE}
      --namespace prometheus-exporters
      charts/${CHART_NAME}
      -f charts/${CHART_NAME}/conf/${CI_ENVIRONMENT_SLUG}/${CLUSTER_NAME}.yaml
      -f ${!access_config}
      --atomic
      --wait

################  SIRIUS  ################

sirius postfix-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-postfix-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius elasticsearch-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius postgres-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius postgres-exporter stage:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: stage
  tags:
    - kube-ci

sirius redis-node-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-redis-node-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

#sirius redis-exporter prod:
#  extends:
#    - .prepare-deploy
#    - .script-deploy
#  stage: sirius
#  variables:
#    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: prod
#  tags:
#    - kube-ci

#sirius redis-exporter stage:
#  extends:
#    - .prepare-deploy
#    - .script-deploy
#  stage: sirius
#  variables:
#    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: stage
#  tags:
#    - kube-ci