stages:
  - cpm-dev-deploy
  - corp-deploy
  - univ-deploy
  - cpm-yc-deploy
  - sirius-deploy

.base-deploy:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
    - echo 'CI_ENVIRONMENT_SLUG =>' ${CI_ENVIRONMENT_SLUG}
    - echo 'CHART_NAME =>' ${CHART_NAME}
  script:
    - set -x
    - kubectl get ns prometheus-exporters-${CI_ENVIRONMENT_SLUG} || kubectl create ns prometheus-exporters-${CI_ENVIRONMENT_SLUG}
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="${CHART_NAME}"
      NAMESPACE="prometheus-exporters-${CI_ENVIRONMENT_SLUG}"
      CHART="deploy/helm/charts/${CHART_NAME}"
      HELM_ARGS="
      -f deploy/helm/charts/${CHART_NAME}/conf/${CI_ENVIRONMENT_SLUG}/${CLUSTER_NAME}.yaml
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${GITLAB_REGISTRY}"
      --set global.ngenix_user_login="${NGENIX_USER_LOGIN}"
      --set global.ngenix_user_token="${NGENIX_USER_TOKEN}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

################  CPM-DEV  ################

cpm-dev elasticsearch-exporter deploy:
  extends:
    - .base-deploy
  stage: cpm-dev-deploy
  variables:
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "cpm-dev"
  environment:
    name: stage
  tags:
    - kube-cpm

################  CPM-YC  ################

cpm-yc elasticsearch-exporter deploy:
  extends:
    - .base-deploy
  stage: cpm-yc-deploy
  variables:
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "cpm"
  environment:
    name: prod
  tags:
    - cpm-yac

#cpm-yc ngenix-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: cpm-yc-deploy
#  variables:
#    CHART_NAME: "prometheus-ngenix-exporter"
#    CLUSTER_NAME: "cpm"
#  environment:
#    name: prod
#  tags:
#    - cpm-yac

#cpm-yc redis-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: cpm-yc-deploy
#  variables:
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "cpm"
#  environment:
#    name: prod
#  tags:
#    - cpm-yac

#cpm-yc postgres-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: cpm-yc-deploy
#  variables:
#    CHART_NAME: "prometheus-postgres-exporter"
#    CLUSTER_NAME: "cpm"
#  environment:
#    name: prod
#  tags:
#    - cpm-yac

################  CORP  ################

corp elasticsearch-exporter deploy:
  extends:
    - .base-deploy
  stage: corp-deploy
  variables:
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "corp"
  environment:
    name: prod
  tags:
    - kube-corp

#corp ngenix-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: corp-deploy
#  variables:
#    CHART_NAME: "prometheus-ngenix-exporter"
#    CLUSTER_NAME: "corp"
#  environment:
#    name: prod
#  tags:
#    - kube-corp

#corp prod postgres-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: corp-deploy
#  variables:
#    CHART_NAME: "prometheus-postgres-exporter"
#    CLUSTER_NAME: "corp"
#  environment:
#    name: prod
#  tags:
#    - kube-corp

#corp prod redis-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: corp-deploy
#  variables:
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "corp"
#  environment:
#    name: prod
#  tags:
#    - kube-corp

#################  UNIV  ################

univ elasticsearch-exporter deploy:
  extends:
    - .base-deploy
  stage: univ-deploy
  variables:
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: prod
  tags:
    - kube-univ

#univ ngenix-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: univ-deploy
#  variables:
#    CHART_NAME: "prometheus-ngenix-exporter"
#    CLUSTER_NAME: "univ"
#  environment:
#    name: prod
#  tags:
#    - kube-univ

#univ prod postgres-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: univ-deploy
#  variables:
#    CHART_NAME: "prometheus-postgres-exporter"
#    CLUSTER_NAME: "univ"
#  environment:
#    name: prod
#  tags:
#    - kube-univ

#univ stage postgres-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: univ-deploy
#  variables:
#    CHART_NAME: "prometheus-postgres-exporter"
#    CLUSTER_NAME: "univ"
#  environment:
#    name: stage
#  tags:
#    - kube-univ

#univ prod redis-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: univ-deploy
#  variables:
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "univ"
#  environment:
#    name: prod
#  tags:
#    - kube-univ

#univ stage redis-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: univ-deploy
#  variables:
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "univ"
#  environment:
#    name: stage
#  tags:
#    - kube-univ

################  SIRIUS  ################

sirius elasticsearch-exporter deploy:
  extends:
    - .base-deploy
  stage: sirius-deploy
  variables:
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

#sirius ngenix-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: sirius-deploy
#  variables:
#    CHART_NAME: "prometheus-ngenix-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: prod
#  tags:
#    - kube-ci

#sirius prod postgres-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: sirius-deploy
#  variables:
#    CHART_NAME: "prometheus-postgres-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: prod
#  tags:
#    - kube-ci

#sirius stage postgres-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: sirius-deploy
#  variables:
#    CHART_NAME: "prometheus-postgres-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: stage
#  tags:
#    - kube-ci

#sirius prod redis-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: sirius-deploy
#  variables:
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: prod
#  tags:
#    - kube-ci

#sirius stage redis-exporter deploy:
#  extends:
#    - .base-deploy
#  stage: sirius-deploy
#  variables:
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: stage
#  tags:
#    - kube-ci
