stages:
  - cpm
  - corp
  - univ
  - sirius

.prepare-deploy:
  when: manual
  before_script:
    - echo 'Deploy parameters:'
    - echo 'CLUSTER_NAME =>' ${CLUSTER_NAME}
    - echo 'CI_ENVIRONMENT_SLUG =>' ${CI_ENVIRONMENT_SLUG}
    - echo 'CHART_NAME =>' ${CHART_NAME}
    - echo 'RELEASE =>' ${RELEASE}
    - kubectl get ns prometheus-exporters || kubectl create ns prometheus-exporters
    - export access_config="${CLUSTER_NAME}_access_config"

.script-deploy:
  script:
    - chmod +x ./scripts/helm_deploy_and_wait.sh
    - RELEASE_NAME="${RELEASE}"
      NAMESPACE="prometheus-exporters"
      CHART="charts/${CHART_NAME}"
      HELM_ARGS="
      -f charts/${CHART_NAME}/conf/${CI_ENVIRONMENT_SLUG}/${CLUSTER_NAME}.yaml
      -f ${!access_config}
      --set global.yc_secret="${YC_REGISTRY}"
      --set global.gitlab_secret="${GITLAB_REGISTRY}"
      --set global.ngenix_user_login="${NGENIX_USER_LOGIN}"
      --set global.ngenix_user_token="${NGENIX_USER_TOKEN}"
      --set global.hosting_secret="${HOSTING_AUTH}"
      --set global.hosting_user="${HOSTING_USER}"
      --atomic
      --wait"
      ./scripts/helm_deploy_and_wait.sh

.helm-deploy:
  script:
    - helm upgrade --install
      ${RELEASE}
      --namespace prometheus-exporters
      charts/${CHART_NAME}
      -f charts/${CHART_NAME}/conf/${CI_ENVIRONMENT_SLUG}/${CLUSTER_NAME}.yaml
      -f ${!access_config}
      --atomic
      --wait

################  CPM-DEV  ################

#cpm elasticsearch-exporter stage:
#  extends:
#    - .prepare-deploy
#    - .script-deploy
#  stage: cpm
#  variables:
#    RELEASE: "${CHART_NAME}"
#    CHART_NAME: "prometheus-elasticsearch-exporter"
#    CLUSTER_NAME: "cpm_dev"
#  environment:
#    name: stage
#  tags:
#    - kube-cpm

################  CPM-YC  ################

cpm elasticsearch-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: cpm
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "cpm"
  environment:
    name: prod
  tags:
    - cpm-yac

cpm ngenix-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: cpm
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-ngenix-exporter"
    CLUSTER_NAME: "cpm"
  environment:
    name: prod
  tags:
    - cpm-yac

cpm redis-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: cpm
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}" 
    CHART_NAME: "prometheus-redis-exporter"
    CLUSTER_NAME: "cpm"
  environment:
    name: prod
  tags:
    - cpm-yac

cpm postgres-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: cpm
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "cpm"
  environment:
    name: prod
  tags:
    - cpm-yac

################  CORP  ################

corp balancer-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: corp
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-balancer-exporter"
    CLUSTER_NAME: "corp"
  environment:
    name: prod
  tags:
    - kube-corp

corp elasticsearch-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: corp
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "corp"
  environment:
    name: prod
  tags:
    - kube-corp

corp ngenix-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: corp
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-ngenix-exporter"
    CLUSTER_NAME: "corp"
  environment:
    name: prod
  tags:
    - kube-corp

corp postgres-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: corp
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "corp"
  environment:
    name: prod
  tags:
    - kube-corp

corp redis-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: corp
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-redis-exporter"
    CLUSTER_NAME: "corp"
  environment:
    name: prod
  tags:
    - kube-corp

#################  UNIV  ################

univ balancer-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: univ
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-balancer-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: prod
  tags:
    - kube-univ

univ elasticsearch-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: univ
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: prod
  tags:
    - kube-univ

univ ngenix-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: univ
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-ngenix-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: prod
  tags:
    - kube-univ

univ postgres-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: univ
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: prod
  tags:
    - kube-univ

univ postgres-exporter stage:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: univ
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: stage
  tags:
    - kube-univ

univ redis-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: univ
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-redis-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: prod
  tags:
    - kube-univ

univ redis-exporter stage:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: univ
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-redis-exporter"
    CLUSTER_NAME: "univ"
  environment:
    name: stage
  tags:
    - kube-univ

################  SIRIUS  ################

sirius balancer-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-balancer-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius robot-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-robot-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius runner-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-runner-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius borg-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-borg-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius postfix-exporter prod:
  extends:
    - .prepare-deploy
    - .helm-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-postfix-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius elasticsearch-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-elasticsearch-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius ngenix-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-ngenix-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius postgres-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

sirius postgres-exporter stage:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
    CHART_NAME: "prometheus-postgres-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: stage
  tags:
    - kube-ci

sirius redis-node-exporter prod:
  extends:
    - .prepare-deploy
    - .script-deploy
  stage: sirius
  variables:
    RELEASE: "${CHART_NAME}"
    CHART_NAME: "prometheus-redis-node-exporter"
    CLUSTER_NAME: "sirius"
  environment:
    name: prod
  tags:
    - kube-ci

#sirius redis-exporter prod:
#  extends:
#    - .prepare-deploy
#    - .script-deploy
#  stage: sirius
#  variables:
#    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: prod
#  tags:
#    - kube-ci

#sirius redis-exporter stage:
#  extends:
#    - .prepare-deploy
#    - .script-deploy
#  stage: sirius
#  variables:
#    RELEASE: "${CHART_NAME}-${CI_ENVIRONMENT_SLUG}"
#    CHART_NAME: "prometheus-redis-exporter"
#    CLUSTER_NAME: "sirius"
#  environment:
#    name: stage
#  tags:
#    - kube-ci
