apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "prometheus-ngenix-exporter.labels" . | nindent 4 }}
    name: {{ template "prometheus-ngenix-exporter.name" . }}
  name: {{ template "prometheus-ngenix-exporter.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: health
      port: 11020
      protocol: TCP
      targetPort: 11020
  selector:
    {{- include "prometheus-ngenix-exporter.selectorLabels" . | nindent 4 }}
    app: {{ template "prometheus-ngenix-exporter.name" . }}
  sessionAffinity: None

