apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: {{ template "prometheus-ngenix-exporter.name" . }}
    release: {{ .Release.Namespace }}
  name: {{ template "prometheus-ngenix-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
    - honorLabels: true
      interval: 60s
      path: /_metrics
      port: health
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "prometheus-ngenix-exporter.selectorLabels" . | nindent 6 }}
