{{- if .Values.secrets.enabled -}}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.global.gitlab_secret }}
kind: Secret
metadata:
  name: gitlab-registry
  labels:
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
{{- end }}