---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.redis_ci_1.node }}-node-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.redis_ci_1.ip }}
    nodeName: {{ .Values.endpoints.redis_ci_1.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.redis_ci_2.node }}-node-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.redis_ci_2.ip }}
    nodeName: {{ .Values.endpoints.redis_ci_2.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.redis_ci_3.node }}-node-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.redis_ci_3.ip }}
    nodeName: {{ .Values.endpoints.redis_ci_3.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
