---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "prometheus-redis-node-exporter.labels" . | nindent 4 }}
    node: {{ .Values.endpoints.redis_ci_1.node }}
  name: prometheus-{{ .Values.endpoints.redis_ci_1.node }}-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  sessionAffinity: None
  type: {{ .Values.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "prometheus-redis-node-exporter.labels" . | nindent 4 }}
    node: {{ .Values.endpoints.redis_ci_2.node }}
  name: prometheus-{{ .Values.endpoints.redis_ci_2.node }}-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  sessionAffinity: None
  type: {{ .Values.service.type }}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "prometheus-redis-node-exporter.labels" . | nindent 4 }}
    node: {{ .Values.endpoints.redis_ci_3.node }}
  name: prometheus-{{ .Values.endpoints.redis_ci_3.node }}-node-exporter
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  sessionAffinity: None
  type: {{ .Values.service.type }}
