{{- if .Values.endpoints.uranus }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.uranus.node }}-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.uranus.ip }}
    nodeName: {{ .Values.endpoints.uranus.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
{{- end }}

{{- if or (and .Values.endpoints.pluto .Values.endpoints.uranus) (.Values.endpoints.pluto) }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.pluto.node }}-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.pluto.ip }}
    nodeName: {{ .Values.endpoints.pluto.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
{{- end }}

{{- if .Values.endpoints.univ }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.univ.node }}-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.univ.ip }}
    nodeName: {{ .Values.endpoints.univ.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
{{- end }}
