---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.uranus.node }}-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.service.uranus.ip }}
    nodeName: {{ .Values.endpoints.uranus.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP

---

apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-{{ .Values.endpoints.pluto.node }}-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.service.pluto.ip }}
    nodeName: {{ .Values.endpoints.pluto.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
