# Политика загрузки образа
imagePullPolicy: Always

# Имя образа и тэг-версия
image: registry.sirius.online/infra/exporters/ngenix-exporter
imageTag: v0.15
#imageTag: latest

# Секреты для доступа к реджисти с образом
imagePullSecrets:
  - name: gitlab-registry

# ID конфигурации Ngenix
config_ids: {}

# Выделяемые ресурсы
resources:
  requests:
    memory: 100Mi
    cpu: 100m
  limits:
    memory: 300Mi

# Механизм выбора нод для установки
nodeSelector: {}

# Настройка невосприимчивости к теинтам нодж
tolerations:
  - effect: NoSchedule
    key: node-role
    operator: Equal
    value: monitoring

# Настройки сервиса
service:
  type: ClusterIP

# Настройки сервиссмонитора
servicemonitor:
  release: rancher-monitoring
