# Настройки эндпоинта
endpoints:
  uranus:
    ip: 192.168.88.1
    node: balancer-uranus
  pluto:
    ip: 192.168.88.2
    node: balancer-pluto

# Настройки сервиса
service:
  name: metrics
  type: ClusterIP
  port: 4040

# Настройки сервисмонитора:
serviceMonitor:
  interval: 60s
  path: /metrics
  port: metrics
  scheme: http
