# Настройки эндпоинта

# Настройки сервиса
service:
  name: metrics
  type: ClusterIP
  port: 4040

# Настройки сервисмонитора:
serviceMonitor:
  interval: 60s
  path: /metrics
  port: metrics
  scheme: http

# Включаем ли мы секреты
secrets:
  enabled: true