---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-hosting_controller-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.hosting_controller.ip }}
    nodeName: {{ .Values.endpoints.hosting_controller.node }}
  ports:
  - name: {{ .Values.service.hosting_controller.name }}
    port: {{ .Values.service.hosting_controller.port }}
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: prometheus-hosting_k8s-exporter
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.hosting_k8s.ip }}
    nodeName: {{ .Values.endpoints.hosting_k8s.node }}
  ports:
  - name: {{ .Values.service.hosting_k8s.name }}
    port: {{ .Values.service.hosting_k8s.port }}
    protocol: TCP

