apiVersion: v1
kind: Endpoints
metadata:
  labels:
    {{- include "prometheus-postfix-exporter.labels" . | nindent 4 }}
  name: {{ template "prometheus-postfix-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ .Values.endpoints.ip }}
    nodeName: {{ .Values.endpoints.node }}
  ports:
  - name: {{ .Values.service.name }}
    port: {{ .Values.service.port }}
    protocol: TCP
