apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    {{- include "prometheus-postfix-exporter.labels" . | nindent 4 }}
  name: {{ template "prometheus-postfix-exporter.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  endpoints:
  - interval: 60s
    metricRelabelings:
    - action: keep
      regex: postfix.*
      sourceLabels:
      - __name__
    path: /metrics
    port: metrics
    scheme: http
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      {{- include "prometheus-postfix-exporter.selectorLabels" . | nindent 6 }}
