{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- if .Values.networkPolicy.labels }}
      {{ toYaml .Values.networkPolicy.labels | indent 4 }}
    {{- end }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}
      release: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
      - port: {{ .Values.service.targetPort }}
{{- end }}
